---
- name: implementing docker compose using ansible playbooks
  hosts: all
  tasks:
    - name: create a mysql container
      docker_container:
        name: mydb
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: harshi

    - name: Create a wordpress container
      docker_container:
        name: wordpress
        image: wordpress
        ports:
          - 8888:80
        links:
          - mydb:mysql
...
