---
- name: install docker on all servers
  hosts: all
  tasks:
    - name: download the docker script and execute it
      shell: "{{item}}"
      with_items:
        - curl -fsSL https://get.docker.com -o install-docker.sh
        - sudo sh install-docker.sh
