---
- name: create 10 nginx containers for load balancing on all servers
  hosts: all
  tasks:
    - name: create 10 nginx containers
      docker_container:
        image: nginx
        name: "container{{item}}"
      with_sequence: count=10
