--- 
- name: implementing loops
  hosts: all
  tasks:
    - name: install s/w's
      apt:
        name: "{{item}}"
        state: present
        update_cache: no
      with_items:
        - tree
        - git
        - maven

...
