---
- name: install git on all servers
  hosts: all
  tasks:
    - name: install git on ubuntu using apt
      apt:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: install git on rehat using yum
      yum:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"
