---
- name: implementing host scope variables
  hosts: 172.31.19.108   
  tasks:
    - name: user creation
      user:
        name: "{{a}}"
        password: "{{b}}"
        uid: "{{c}}"
        home: "{{d}}"
        comment: "{{e}}"
        shell: "{{f}}"
...
