---
- name: configure tomcat
  hosts: all
  tasks:
    - name: install tomcat10
      apt:
        name: tomcat10
        state: present
        update_cache: yes
    - name: install tomcat10-admin
      apt:
        name: tomcat10-admin
        state: present
        update_cache: yes
    - name: copy customised tomcat-users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat10
    - name: change port of tomcat from 8080 to 9090
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat10/server.xml
    - name: restart tomcat10
      service:
        name: tomcat10
        state: restarted
    - name: pause for 40 sec
      pause:
        seconds: 40
    - name: check tomcat10 on server1
      uri:
        url: http://172.31.21.137:9090
        status_code: 200
    - name: check tomcat10 on server2
      uri:
        url: http://172.31.18.79:9090
        status_code: 200
...
