---
- name: implementing tags
  hosts: all
  gather_facts: false
  become: yes
  tasks: 
    - name: create user
      user:
        name: ragav
        password: intell
      tags: user_creation
    - name: install tree
      apt:
        name: tree
        state: present
        update_cache: yes
      tags:
        - tree_installation
        - never
    - name: copy password file
      copy: 
        src: /etc/passwd
        dest: /tmp
...  
